### ISSUE TITLE
Problem AFK continues.

### ISSUE THREAD

**Issue by Iniciando** [Smokexyz/HerculesBG#2]
I performed new tests and the AFK problem described in the other issue persists.

When the player joins the battlefield, if he is stopped / seated at the time of registration and the game starts, he is expelled from the battle. That is, the inactive time (AFK) is being counted off the BG map.

When thrown out of the battlefield due to not moving (AFK), sometimes the kicked player gets stuck at his return point, and still remains in the guild, as if he were inside the BG map.

Spoiler Show
https://postimg.org/image/tnozymb0d

**NEW**

* I also remembered that a warning message is being sent to the player that he will be teleported for being AFK, giving him an opportunity to move, and if he does not move, kicke the player.

* I think you have forgotten 2 files in the db folder, as can be seen in the official eAmod repository.
Item_db and mob_db
https://github.com/zephyrus-cr/eamod/tree/master/Diffs/battleground/db

**Comment by Smokexyz** [comment]
Are you sure you're using the latest src for the plugin? Please recompile and test this again.

**Comment by Iniciando** [comment]
Yes, I just tested again and the problem persists. Some errors are being presented on map-server also ...

[Error]: script error in file 'npc/custom/hBG/bg_tierra_ti.txt' line 111 column
1
    set_label: dup label
   108:         end;
   109:
   110: OnTimer900000:
*  111: OnMatchEnd:
        ^
   112:         stopnpctimer;
   113:         cleanmap "region_8"; // Removes all ground items
   114:         donpcevent "#gti_respawn::OnBGStop";

[Error]: quest_add: Character 150000 already has quest 8506.
[Error]: quest_add: Character 150002 already has quest 8506.
[Error]: quest_add: Character 150000 already has quest 8506.

**Comment by Smokexyz** [comment]
Fixed all problems.
