### ISSUE TITLE
Compiling Plugin error

### ISSUE THREAD

**Issue by wlauton** [Smokexyz/HerculesBG#6]
New herc and hBG.c compiling error:

1>------ Build started: Project: hBG, Configuration: Release Win32 ------
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>  hBG.c
1>..\src\plugins\hBG.c(1071): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2049): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2050): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2523): warning C4018: '>=' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2581): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2587): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(2593): error C2143: syntax error : missing ';' before 'type'
1>..\src\plugins\hBG.c(2594): error C2065: 'i' : undeclared identifier
1>..\src\plugins\hBG.c(2595): error C2065: 'i' : undeclared identifier
1>..\src\plugins\hBG.c(2614): error C2143: syntax error : missing ';' before 'type'
1>..\src\plugins\hBG.c(2615): error C2143: syntax error : missing ';' before 'type'
1>..\src\plugins\hBG.c(2617): error C2065: 'i' : undeclared identifier
1>..\src\plugins\hBG.c(2618): error C2065: 'i' : undeclared identifier
1>..\src\plugins\hBG.c(2621): error C2065: 'pos' : undeclared identifier
1>..\src\plugins\hBG.c(2621): error C2065: 'i' : undeclared identifier
1>..\src\plugins\hBG.c(2623): error C2065: 'qm' : undeclared identifier
1>..\src\plugins\hBG.c(2623): error C2065: 'pos' : undeclared identifier
1>..\src\plugins\hBG.c(2623): warning C4047: '=' : 'int' differs in levels of indirection from 'hBG_queue_member *'
1>..\src\plugins\hBG.c(2623): warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
1>..\src\plugins\hBG.c(2623): error C2223: left of '->sd' must point to struct/union
1>..\src\plugins\hBG.c(2717): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(3722): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(3724): warning C4018: '<' : signed/unsigned mismatch
1>..\src\plugins\hBG.c(3862): warning C4018: '<' : signed/unsigned mismatch
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Smokexyz** [comment]
Cannot be reproduced, please pull the latest repo from this repository and try again.
